"""Assemble docs/schema_snapshot.sql from an MCP execute_sql result file.

Sandbox workaround for /refresh-schema: asyncpg / venv python are unavailable
here, so refresh_schema.py's per-table formatting is reproduced server-side in
SQL (returned as `full_body`) and this stdlib-only helper wraps it with the
standard header, byte-matching refresh_schema.py's output.
"""
import json, pathlib, re

src = pathlib.Path(
    "/home/joe/.claude/projects/-mnt-c-Users-Joe-2ndActCapital/"
    "0a27b940-54e4-4d27-a92d-8ecd25286261/tool-results/"
    "mcp-supabase-2ndact-dev-execute_sql-1785268315767.txt"
)
outer = json.loads(src.read_text())
result_text = outer["result"]
m = re.search(r"<untrusted-data-[^>]+>\s*(\[.*\])\s*</untrusted-data-", result_text, re.S)
rows = json.loads(m.group(1))
full_body = rows[0]["data"]["full_body"]

header = (
    "-- Schema snapshot — auto-generated by scripts/refresh_schema.py\n"
    "-- DO NOT EDIT BY HAND.\n"
    "-- Regenerate: cd apps/api && DATABASE_URL='...' python scripts/refresh_schema.py\n"
    "\n"
)
content = header + full_body + "\n"
out = pathlib.Path("/mnt/c/Users/Joe/2ndActCapital/docs/schema_snapshot.sql")
out.write_text(content)
print("wrote", out)
print("chars", len(content), "lines", content.count("\n"))
