"""Regenerate docs/schema_snapshot.sql from the live deployed database.

Run from apps/api/:
    DATABASE_URL='postgresql://...' python scripts/refresh_schema.py

Writes the snapshot to docs/schema_snapshot.sql at the repo root.
PgBouncer-safe: statement_cache_size=0.
"""
import asyncio
import glob
import os
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
API_ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_FILE = REPO_ROOT / "docs" / "schema_snapshot.sql"


def _bootstrap_env() -> None:
    """Make `python3 scripts/refresh_schema.py` self-sufficient: put the venv
    site-packages on the path (asyncpg) and load apps/api/.env if present."""
    for sp in glob.glob(str(API_ROOT / "venv" / "lib" / "python*" / "site-packages")):
        if sp not in sys.path:
            sys.path.insert(0, sp)
    env_path = API_ROOT / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k, v)


async def main() -> None:
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        sys.exit("DATABASE_URL is not set.")

    import asyncpg

    conn = await asyncpg.connect(database_url, statement_cache_size=0, ssl="require")

    tables = await conn.fetch(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_type = 'BASE TABLE'
        ORDER BY table_name
        """
    )

    lines: list[str] = [
        "-- Schema snapshot — auto-generated by scripts/refresh_schema.py",
        "-- DO NOT EDIT BY HAND.",
        "-- Regenerate: cd apps/api && DATABASE_URL='...' python scripts/refresh_schema.py",
        "",
    ]

    for (table_name,) in tables:
        lines.append(f"-- ===== {table_name} =====")
        cols = await conn.fetch(
            """
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns
            WHERE table_name   = $1
              AND table_schema = 'public'
            ORDER BY ordinal_position
            """,
            table_name,
        )
        for c in cols:
            nullable = "" if c["is_nullable"] == "YES" else " NOT NULL"
            default = f" DEFAULT {c['column_default']}" if c["column_default"] else ""
            lines.append(f"--   {c['column_name']:40s} {c['data_type']}{nullable}{default}")

        constraints = await conn.fetch(
            """
            SELECT tc.constraint_type, tc.constraint_name, kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema    = kcu.table_schema
            WHERE tc.table_name   = $1
              AND tc.table_schema = 'public'
              AND tc.constraint_type IN ('UNIQUE', 'PRIMARY KEY')
            ORDER BY tc.constraint_name, kcu.ordinal_position
            """,
            table_name,
        )
        if constraints:
            by_constraint: dict[str, list[str]] = {}
            by_type: dict[str, str] = {}
            for c in constraints:
                by_constraint.setdefault(c["constraint_name"], []).append(c["column_name"])
                by_type[c["constraint_name"]] = c["constraint_type"]
            for cname, ccols in by_constraint.items():
                ctype = by_type[cname]
                lines.append(f"--   {ctype} {cname}: ({', '.join(ccols)})")

        lines.append("")

    await conn.close()

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    _bootstrap_env()
    asyncio.run(main())
