"""verify_litellmphaseb.py — LiteLLM Phase B: text calls routed through LiteLLM.

WHAT THIS PROVES, and — just as importantly — WHAT IT CANNOT PROVE TODAY.

The sprint asked for a real, successful extraction call through the live LiteLLM
proxy. That is NOT possible right now, and this script proves WHY with live
measurements rather than asserting it away. Three independent, real, external
blockers, each requiring console/human action (see the BLOCKED banner printed at
the end):

  B1. The live proxy has ZERO model deployments. `GET /v1/models` returns an
      empty list and `GET /model/info` returns HTTP 500 "LLM Model List not
      loaded in". LiteLLM cannot route ANY model name today.
  B2. Doppler's `LITELLM_MASTER_KEY` is NOT the proxy's master key. LiteLLM
      reports `role=internal_user` and refuses `/model/new` with HTTP 403
      "You can only make model calls if you are a PROXY_ADMIN". So this sprint
      cannot fix B1 either — adding a deployment needs the real PROXY_ADMIN key.
  B3. `ANTHROPIC_API_KEY` exists NOWHERE — not in Doppler prd (35 secrets, all
      names enumerated), not in ~/.bashrc, not in apps/api/.env. So neither
      LiteLLM's upstream nor the direct-Anthropic rollback path has a
      credential to call a model with.

What IS proven, for real, against the LIVE proxy at hollisworks-litellm.onrender.com:

  [1-4]  Task 1's four findings, from live introspection of the real file, the
         real deployed proxy and the real Doppler config — not quoted from the
         prompt. Two places where the prompt and reality disagree are reported.
  [5]    Task 2's gap closed: LITELLM_BASE_URL now really exists in Doppler prd.
  [6-7]  Transport selection: LiteLLM by default when configured, direct
         Anthropic when the Task-4 rollback switch is engaged.
  [8-9]  THE ROUTING GENUINELY WORKS AT THE TRANSPORT LAYER. A real call through
         the real `_execute_chain` reaches the real proxy over the network, and
         we know it reached LiteLLM specifically because the error text coming
         back ("Invalid model name passed in model=...") is generated by LiteLLM
         itself — Anthropic's API does not produce that string, and neither does
         our code. The chain then walks EVERY model, via LiteLLM, exactly as it
         did before this sprint.
  [10]   ai_decision_log's shape is unchanged, proven column-by-column against a
         real PRE-EXISTING row written before this sprint.
  [11]   DUAL VISIBILITY IS REAL. The same call lands in BOTH logs: ours
         (ai_decision_log) and LiteLLM's own (litellm."LiteLLM_SpendLogs"),
         naming the exact models the chain walked, in the same order, agreeing
         on the outcome. NOTE, measured not assumed: LiteLLM flushes that table
         ASYNCHRONOUSLY several seconds after answering, so both the presence
         and the absence assertions poll across a real flush window. A naive
         before/after count taken around the call sees nothing and would have
         reported a false negative — an earlier draft of this script did exactly
         that.
  [12]   The rollback path really bypasses LiteLLM — proven by the client's real
         base_url AND by zero rows in LiteLLM's own spend log after waiting the
         FULL flush window. That absence means something only because [11] just
         proved the same log does capture our calls.
  [12-13] A wrong master key fails LOUD and specifically, and that failure is
         NOT flattened into the ordinary `None` return by the public wrappers.
  [14]   Teardown: zero leftover rows.

Run:  python3 apps/api/scripts/verify_litellmphaseb.py
Never prints LITELLM_MASTER_KEY or any other secret value.
"""
from __future__ import annotations

import asyncio
import io
import json
import contextlib
import os
import pathlib
import re
import sys
import urllib.error
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _db_bootstrap import bootstrap_async  # noqa: E402  (also puts apps/api on sys.path)

API_DIR = pathlib.Path(__file__).resolve().parents[1]
EXTRACTION_PY = API_DIR / "services" / "extraction.py"

ORG_ID = "00000000-0000-0000-0000-000000000001"
TEST_TASK_TYPE = "verify_litellmphaseb"
BOGUS_PRIMARY = "verify-litellmphaseb-nonexistent-model"

RESULTS: list[tuple[bool, str]] = []
BLOCKED: list[str] = []


def check(ok: bool, label: str) -> bool:
    RESULTS.append((bool(ok), label))
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}")
    return bool(ok)


def blocked(label: str, why: str) -> None:
    BLOCKED.append(f"{label} — {why}")
    print(f"  [BLOCKED] {label}\n            {why}")


def http(path: str, *, key: str, method: str = "GET", body=None, timeout=120):
    """Returns (status, text). Never raises, never prints the key."""
    base = os.environ.get("LITELLM_BASE_URL", "").rstrip("/")
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(f"{base}{path}", data=data, method=method)
    req.add_header("Accept", "application/json")
    if key:
        req.add_header("Authorization", f"Bearer {key}")
    if data:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, r.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", "replace")
    except Exception as e:  # noqa: BLE001
        return None, f"{type(e).__name__}: {e}"


async def spend_log_count(conn) -> int:
    """Rows in LiteLLM's OWN spend log. Schema-qualified — app_service's
    search_path does not include the litellm schema (design doc §2)."""
    return await conn.fetchval('SELECT count(*) FROM litellm."LiteLLM_SpendLogs"')


# LiteLLM writes LiteLLM_SpendLogs ASYNCHRONOUSLY, a few seconds after it answers
# the request. Measured, not assumed: a naive before/after count taken around a
# call sees no change, while the rows appear ~2-10s later. Any assertion about
# that log — presence OR absence — has to wait out this window, or it proves
# nothing. Absence checks below deliberately wait the FULL window.
SPEND_LOG_FLUSH_SECONDS = 45


async def spend_rows_since(conn, since, models=None):
    """LiteLLM's own spend-log rows since ``since`` (naive UTC), optionally
    filtered to specific model names."""
    if models:
        return await conn.fetch(
            'SELECT request_id, model, status, spend, "startTime" '
            'FROM litellm."LiteLLM_SpendLogs" '
            'WHERE "startTime" >= $1 AND model = ANY($2::text[]) '
            'ORDER BY "startTime" ASC', since, list(models))
    return await conn.fetch(
        'SELECT request_id, model, status, spend, "startTime" '
        'FROM litellm."LiteLLM_SpendLogs" WHERE "startTime" >= $1 '
        'ORDER BY "startTime" ASC', since)


async def wait_for_spend_rows(conn, since, models, *, expect,
                              timeout=SPEND_LOG_FLUSH_SECONDS):
    """Poll until ``expect`` rows appear, or the flush window expires.

    Returns the rows found. When ``expect`` is 0 this waits the FULL window on
    purpose: an absence assertion that does not outlast the flush lag is
    indistinguishable from simply having looked too early.
    """
    import time as _t
    deadline = _t.monotonic() + timeout
    rows = []
    while _t.monotonic() < deadline:
        rows = await spend_rows_since(conn, since, models)
        if expect and len(rows) >= expect:
            return rows
        await asyncio.sleep(2)
    return rows


async def main() -> int:
    db_url = await bootstrap_async(quiet=True)
    if not db_url:
        print("FATAL: no working DATABASE_URL from Doppler.")
        return 2

    import asyncpg

    import services.extraction as ex

    conn = await asyncpg.connect(db_url, statement_cache_size=0, ssl="require",
                                 timeout=30)

    # A pre-existing ai_decision_log row, captured BEFORE this sprint writes
    # anything, is the baseline that assertion [10] compares against.
    baseline_row = await conn.fetchrow(
        "SELECT * FROM ai_decision_log ORDER BY created_at ASC LIMIT 1")
    spend_before_all = await spend_log_count(conn)
    run_started_at = await conn.fetchval(
        "SELECT (now() AT TIME ZONE 'utc')::timestamp")

    try:
        # ------------------------------------------------------------------
        print("\n=== TASK 1a — the chokepoint, re-confirmed against the real file ===")
        src = EXTRACTION_PY.read_text()
        sdk_imports = re.findall(r"^\s*import anthropic as _anthropic", src, re.M)
        check(len(sdk_imports) == 1,
              f"Anthropic SDK imported in exactly ONE place in extraction.py "
              f"(found {len(sdk_imports)})")
        repo_root = API_DIR.parent.parent
        other = []
        for p in (API_DIR / "services", API_DIR / "routers"):
            for f in p.rglob("*.py"):
                if f == EXTRACTION_PY:
                    continue
                if re.search(r"^\s*import anthropic|^\s*from anthropic",
                             f.read_text(), re.M):
                    other.append(str(f.relative_to(repo_root)))
        check(not other, f"no other service/router imports the Anthropic SDK "
                         f"(found {other or 'none'})")

        for fn in ("call_claude_json", "call_claude_text", "call_claude_with_tools"):
            check(hasattr(ex, fn), f"public helper {fn} still exists")
        check(callable(getattr(ex, "_execute_chain", None)),
              "all three helpers still funnel through the single _execute_chain")

        chain = await ex.resolve_fallback_chain(ORG_ID)
        primary = await ex.resolve_model(ORG_ID)
        check(isinstance(chain, list) and all(isinstance(m, str) for m in chain),
              f"ai.model.fallback_chain reads live as an ordered list: {chain}")
        check(ex.FALLBACK_CHAIN_KEY == "ai.model.fallback_chain",
              "the live chain key is ai.model.fallback_chain (NOT the dead "
              "ai.model.provider / ai.model.fallback)")
        print(f"    live primary for the default org: {primary}")

        # ------------------------------------------------------------------
        print("\n=== TASK 1b — LiteLLM's REAL endpoint shape, measured live ===")
        key = os.environ.get("LITELLM_MASTER_KEY", "")
        s, _ = http("/health/liveliness", key=key)
        check(s == 200, f"proxy is live: GET /health/liveliness -> {s}")

        s_v1, b_v1 = http("/v1/chat/completions", key=key, method="POST", body={
            "model": "probe", "messages": [{"role": "user", "content": "hi"}]})
        s_bare, _ = http("/chat/completions", key=key, method="POST", body={
            "model": "probe", "messages": [{"role": "user", "content": "hi"}]})
        check(s_v1 == s_bare == 400,
              f"BOTH /v1/chat/completions and /chat/completions are mounted and "
              f"equivalent (each -> {s_v1}/{s_bare}); the proxy answers, it does "
              f"not 404")
        s_msg, b_msg = http("/v1/messages", key=key, method="POST", body={
            "model": "probe", "max_tokens": 8,
            "messages": [{"role": "user", "content": "hi"}]})
        check(s_msg == 400 and "anthropic_messages" in b_msg,
              "an Anthropic-SHAPED POST /v1/messages is really parsed and routed "
              "by LiteLLM (it answers 'anthropic_messages: ...') — this is the "
              "route Phase B uses, so the SDK's response objects stay genuine")

        s_models, b_models = http("/v1/models", key=key)
        model_list = json.loads(b_models).get("data", []) if s_models == 200 else None
        check(s_models == 200, f"GET /v1/models answers {s_models}")
        if model_list == []:
            blocked("B1: LiteLLM has ZERO model deployments configured",
                    "GET /v1/models -> {\"data\":[],...} and GET /model/info -> 500 "
                    "'LLM Model List not loaded in'. No model name can be routed, "
                    "so no successful text call is possible through the proxy.")
        check(model_list is not None,
              f"model deployment list read from the live proxy: {model_list}")

        s_new, b_new = http("/model/new", key=key, method="POST", body={
            "model_name": "verify-probe",
            "litellm_params": {"model": "anthropic/claude-haiku-4-5-20251001"}})
        if s_new == 403 and "PROXY_ADMIN" in b_new:
            blocked("B2: Doppler's LITELLM_MASTER_KEY is NOT the proxy master key",
                    "POST /model/new -> 403 'Your role=internal_user ... only if "
                    "you are a PROXY_ADMIN'. It is a virtual/internal-user key. "
                    "This sprint therefore cannot fix B1, and it also means "
                    "litellm.reload_model_cost_map will STILL fail after this "
                    "sprint's LITELLM_BASE_URL fix — contrary to render.yaml's note.")
        check(s_new in (403, 200),
              f"POST /model/new answered {s_new} (recorded, not assumed)")
        check(s_new != 200,
              "no model deployment was created by this verify run (nothing to "
              "clean up on the live proxy)")

        # ------------------------------------------------------------------
        print("\n=== TASK 1c / TASK 2 — Doppler config, and the gap this sprint closed ===")
        check(bool(os.environ.get("LITELLM_BASE_URL")),
              "LITELLM_BASE_URL is PRESENT in Doppler prd (it was ABSENT before "
              "this sprint — Task 2 gap genuinely closed)")
        check(bool(os.environ.get("LITELLM_MASTER_KEY")),
              "LITELLM_MASTER_KEY is PRESENT in Doppler prd")
        check(os.environ.get("LITELLM_BASE_URL", "").startswith("https://"),
              "LITELLM_BASE_URL points at a real https Render URL")
        if not os.environ.get("ANTHROPIC_API_KEY"):
            blocked("B3: ANTHROPIC_API_KEY exists nowhere",
                    "absent from Doppler prd, ~/.bashrc and apps/api/.env. Both "
                    "LiteLLM's upstream and the direct-Anthropic rollback path "
                    "lack a provider credential.")

        # ------------------------------------------------------------------
        print("\n=== TASK 1d — ai_decision_log's shape is untouched ===")
        cols = [r["column_name"] for r in await conn.fetch(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name='ai_decision_log' "
            "ORDER BY ordinal_position")]
        expected = ["id", "org_id", "task_type", "model_requested", "model_used",
                    "fallback_used", "fallback_reason", "cost_usd", "latency_ms",
                    "success", "error_detail", "created_at"]
        check(cols == expected,
              f"ai_decision_log still has exactly its 12 pre-sprint columns in "
              f"order (live: {len(cols)})")
        insert_sql = re.search(r"INSERT INTO ai_decision_log\s*\((.*?)\)",
                               src, re.S).group(1)
        inserted = [c.strip() for c in insert_sql.replace("\n", " ").split(",")]
        check(inserted == expected[1:-1],
              f"_write_ai_decision still inserts the same 10 columns "
              f"(id/created_at defaulted): {inserted}")
        check(baseline_row is not None,
              "a PRE-EXISTING ai_decision_log row exists to compare against")

        # ------------------------------------------------------------------
        print("\n=== TASKS 3 & 4 — transport selection ===")
        os.environ.pop(ex.LITELLM_DISABLE_VAR, None)
        transport, reason = ex.resolve_transport()
        check(transport == ex.TRANSPORT_LITELLM and reason == "",
              "DEFAULT (switch unset, LiteLLM configured) -> transport=litellm")
        client, t, _r, endpoint = ex._build_ai_client()
        check(str(client.base_url).rstrip("/") ==
              os.environ["LITELLM_BASE_URL"].rstrip("/"),
              "the Anthropic SDK client is really pointed at the LiteLLM base URL")
        check(endpoint.endswith("/v1/messages"),
              f"the real request endpoint is LiteLLM's Anthropic route: {endpoint}")
        check("api.anthropic.com" not in str(client.base_url),
              "on the default path the client does NOT point at Anthropic")

        os.environ[ex.LITELLM_DISABLE_VAR] = "1"
        transport, reason = ex.resolve_transport()
        check(transport == ex.TRANSPORT_ANTHROPIC and "rollback" in reason,
              "ROLLBACK (LITELLM_ROUTING_DISABLED=1) -> transport=anthropic, "
              "with a loud reason")
        os.environ["ANTHROPIC_API_KEY"] = "sk-ant-verify-placeholder-not-a-real-key"
        client_rb, t_rb, _r2, endpoint_rb = ex._build_ai_client()
        check("api.anthropic.com" in str(client_rb.base_url),
              "with rollback engaged the client points STRAIGHT at "
              "api.anthropic.com — LiteLLM is not in the path at all")
        check(os.environ["LITELLM_BASE_URL"] not in str(client_rb.base_url),
              "the LiteLLM base URL appears nowhere in the rollback client")
        os.environ.pop(ex.LITELLM_DISABLE_VAR, None)
        os.environ.pop("ANTHROPIC_API_KEY", None)

        transport, reason = ex.resolve_transport()
        saved = os.environ.pop("LITELLM_BASE_URL")
        t_unconf, r_unconf = ex.resolve_transport()
        check(t_unconf == ex.TRANSPORT_ANTHROPIC and "DEGRADED" in r_unconf,
              "UNCONFIGURED LiteLLM degrades to direct Anthropic and says so "
              "LOUDLY (a deploy before the env var lands does not brick AI)")
        os.environ["LITELLM_BASE_URL"] = saved

        # ------------------------------------------------------------------
        print("\n=== TASK 5 — a REAL call, through the REAL chain, to the LIVE proxy ===")
        spend_before = await spend_log_count(conn)
        call_started_at = await conn.fetchval(
            "SELECT (now() AT TIME ZONE 'utc')::timestamp")

        buf = io.StringIO()
        exhausted = None
        with contextlib.redirect_stdout(buf):
            try:
                await ex._execute_chain(
                    task_type=TEST_TASK_TYPE, org_id=ORG_ID,
                    model_key=ex.DEFAULT_MODEL_KEY, model_override=BOGUS_PRIMARY,
                    make_call=lambda c, m: c.messages.create(
                        model=m, max_tokens=16, system="Reply with OK.",
                        messages=[{"role": "user", "content": "ping"}]),
                    extract=lambda msg: msg.content[0].text,
                )
            except ex.AIChainExhausted as exc:
                exhausted = str(exc)
            except Exception as exc:  # noqa: BLE001
                exhausted = f"UNEXPECTED {type(exc).__name__}: {exc}"
        log_text = buf.getvalue()
        print(log_text.rstrip() or "    (no router output)")

        check(exhausted is not None and exhausted.startswith("All models failed"),
              "the real chain executor ran end-to-end and raised AIChainExhausted")
        # THE decisive assertion: this error string is produced by LiteLLM itself.
        # Neither our code nor api.anthropic.com emits "Invalid model name passed
        # in model=" — so seeing it proves the HTTP request really landed on the
        # LiteLLM proxy.
        check("Invalid model name passed in model=" in log_text,
              "the failure text came FROM LITELLM ITSELF ('Invalid model name "
              "passed in model=') — proof the request really reached the live "
              "proxy and was not sent to Anthropic")
        attempted = re.findall(r"\[ai_router\] model '([^']+)' failed", log_text)
        check(len(attempted) >= 2,
              f"the fallback chain genuinely WALKED, via LiteLLM: {attempted}")
        check(attempted[0] == BOGUS_PRIMARY and attempted[1] != BOGUS_PRIMARY,
              f"the forced-failure primary was tried FIRST and the NEXT model in "
              f"the chain was then tried: {attempted[:2]}")
        check(all("via litellm" in line for line in log_text.splitlines()
                  if "] model '" in line),
              "every attempt in the walk is recorded as going via litellm")

        blocked("A successful extraction result through LiteLLM",
                "blocked by B1+B2+B3. The transport is proven to reach LiteLLM "
                "(above); what cannot be proven is a 200 with real generated "
                "text, because the proxy has no model deployment to route to and "
                "no Anthropic credential exists. Needs: PROXY_ADMIN key -> add a "
                "model deployment -> a provider key.")

        # ---- [10] the log row's shape, column-by-column vs the baseline ----
        rows = await conn.fetch(
            "SELECT * FROM ai_decision_log WHERE task_type = $1", TEST_TASK_TYPE)
        check(len(rows) == 1,
              f"exactly ONE ai_decision_log row was written by that call "
              f"(got {len(rows)})")
        if rows and baseline_row is not None:
            new_row = rows[0]
            check(list(new_row.keys()) == list(baseline_row.keys()),
                  "the new row's columns are IDENTICAL to a pre-sprint row's, "
                  "column-by-column")
            same_types = [k for k in new_row.keys()
                          if new_row[k] is not None and baseline_row[k] is not None
                          and type(new_row[k]) is not type(baseline_row[k])]
            check(not same_types,
                  f"every populated column has the same Python type as the "
                  f"pre-sprint row (mismatches: {same_types})")
            check(new_row["model_requested"] == BOGUS_PRIMARY
                  and new_row["success"] is False
                  and new_row["fallback_used"] is True
                  and new_row["error_detail"],
                  "the row's semantics are unchanged: requested/used, "
                  "fallback_used, success=false, error_detail all populated as "
                  "before Phase B")
            check(new_row["org_id"] is not None and new_row["created_at"] is not None,
                  "org_id and created_at are populated by the same defaults")

        # ---- [11] DUAL VISIBILITY: the SAME call in BOTH logs --------------
        # LiteLLM flushes this table asynchronously, so poll rather than peek.
        print(f"    waiting up to {SPEND_LOG_FLUSH_SECONDS}s for LiteLLM to flush "
              f"its own spend log...")
        walked = [BOGUS_PRIMARY, attempted[1]] if len(attempted) >= 2 else attempted
        spend_rows = await wait_for_spend_rows(
            conn, call_started_at, walked, expect=len(walked))
        got_models = [r["model"] for r in spend_rows]
        check(len(spend_rows) >= len(walked),
              f"litellm.LiteLLM_SpendLogs recorded THIS call — "
              f"{len(spend_rows)} row(s) since the call began: {got_models}")
        check(set(got_models) == set(walked),
              f"LiteLLM's OWN log names the EXACT models our chain walked "
              f"({walked}) — the same call is visible in both logs, which is the "
              f"dual-write the design doc §4 asked for")
        check(got_models[:2] == walked[:2] if len(got_models) >= 2 else False,
              f"LiteLLM logged them in the SAME ORDER the chain tried them: "
              f"{got_models[:2]}")
        # Correlate the two logs on the one field they share.
        if rows:
            check(rows[0]["model_requested"] == spend_rows[0]["model"],
                  f"ai_decision_log.model_requested ({rows[0]['model_requested']}) "
                  f"== the first model in LiteLLM's own log "
                  f"({spend_rows[0]['model']}) — the two records are the same event")
        check(all(r["status"] == "failure" for r in spend_rows),
              "LiteLLM records these as status=failure, matching our "
              "ai_decision_log success=false — the two logs AGREE on the outcome")
        check(all(float(r["spend"] or 0) == 0.0 for r in spend_rows),
              "spend=0 on every row: nothing was billed by this verify run")
        all_rows_ever = await conn.fetch(
            'SELECT DISTINCT status FROM litellm."LiteLLM_SpendLogs"')
        statuses = sorted(r["status"] for r in all_rows_ever)
        check(statuses == ["failure"],
              f"EVERY row the proxy has ever written is status=failure "
              f"({statuses}) — independent confirmation of B1: this proxy has "
              f"never successfully routed a single call")

        # ---- rollback really bypasses LiteLLM -----------------------------
        print("\n--- rollback engaged: LiteLLM must not be contacted at all ---")
        spend_rb_before = await spend_log_count(conn)
        rb_started_at = await conn.fetchval(
            "SELECT (now() AT TIME ZONE 'utc')::timestamp")
        os.environ[ex.LITELLM_DISABLE_VAR] = "1"
        buf2 = io.StringIO()
        with contextlib.redirect_stdout(buf2):
            result_rb = await ex._execute_chain(
                task_type=TEST_TASK_TYPE + "_rollback", org_id=ORG_ID,
                model_key=ex.DEFAULT_MODEL_KEY, model_override=BOGUS_PRIMARY,
                make_call=lambda c, m: c.messages.create(
                    model=m, max_tokens=16, system="x",
                    messages=[{"role": "user", "content": "ping"}]),
                extract=lambda msg: msg.content[0].text,
            )
        rb_text = buf2.getvalue()
        os.environ.pop(ex.LITELLM_DISABLE_VAR, None)

        check(result_rb is None and "no usable credential" in rb_text,
              "with rollback engaged and no ANTHROPIC_API_KEY, the call returns "
              "None on the pre-existing no-key contract and says why")
        check("ops rollback engaged" in rb_text,
              "the rollback reason is printed loudly, so a rolled-back "
              "deployment can never be mistaken for a routing one")
        # This absence assertion is only meaningful because the PRESENCE
        # assertion above just proved this same log reliably captures our calls
        # within the flush window. Wait out the FULL window before concluding
        # "nothing arrived".
        print(f"    waiting the full {SPEND_LOG_FLUSH_SECONDS}s flush window to "
              f"prove ABSENCE, not just earliness...")
        rb_spend_rows = await wait_for_spend_rows(
            conn, rb_started_at, [BOGUS_PRIMARY, *chain], expect=0)
        spend_rb_after = await spend_log_count(conn)
        check(not rb_spend_rows,
              f"ZERO rows in LiteLLM's own spend log for the rollback call, after "
              f"waiting the full flush window — LiteLLM was genuinely never "
              f"contacted (found: {[r['model'] for r in rb_spend_rows]})")
        check(spend_rb_after == spend_rb_before,
              f"the spend log's total count is unchanged across the rollback call "
              f"({spend_rb_before} -> {spend_rb_after})")
        check("Invalid model name passed in model=" not in rb_text,
              "no LiteLLM-generated text appears anywhere in the rollback call's "
              "output — independent confirmation the proxy was not in the path")
        rb_rows = await conn.fetchval(
            "SELECT count(*) FROM ai_decision_log WHERE task_type = $1",
            TEST_TASK_TYPE + "_rollback")
        check(rb_rows == 0,
              "the no-credential rollback path writes no log row, exactly as the "
              "pre-sprint no-key path did")
        blocked("The rollback path SUCCEEDING via direct Anthropic",
                "blocked by B3 (no ANTHROPIC_API_KEY anywhere). Proven instead: "
                "the client really points at api.anthropic.com and LiteLLM is "
                "provably never contacted. The remaining unproven step is the "
                "upstream 200.")

        # ---- [12/13] a wrong master key fails loud ------------------------
        print("\n--- a deliberately wrong LITELLM_MASTER_KEY ---")
        import httpx
        import anthropic

        real_401 = anthropic.AuthenticationError(
            "Invalid API key",
            response=httpx.Response(
                401, request=httpx.Request("POST", "https://example.invalid")),
            body=None)
        check(ex._is_auth_failure(real_401),
              "a genuine anthropic.AuthenticationError (HTTP 401) is recognised "
              "as an auth failure")
        check(not ex._is_auth_failure(ValueError("nope")),
              "an ordinary error is NOT misread as an auth failure")

        async def auth_failing_call(_client, _model):
            raise real_401

        buf3 = io.StringIO()
        raised = None
        with contextlib.redirect_stdout(buf3):
            try:
                await ex._execute_chain(
                    task_type=TEST_TASK_TYPE + "_auth", org_id=ORG_ID,
                    model_key=ex.DEFAULT_MODEL_KEY, model_override=BOGUS_PRIMARY,
                    make_call=auth_failing_call, extract=lambda m: m)
            except ex.AILiteLLMAuthError as exc:
                raised = str(exc)
            except Exception as exc:  # noqa: BLE001
                raised = f"WRONG TYPE {type(exc).__name__}: {exc}"
        check(raised is not None and not raised.startswith("WRONG TYPE"),
              "a rejected master key raises AILiteLLMAuthError — it does NOT "
              "silently return None")
        check(raised and "LITELLM_MASTER_KEY" in raised,
              "the message names the exact variable at fault")
        check(raised and "LITELLM_ROUTING_DISABLED=1" in raised,
              "the message states the ACTIONABLE remedy (roll back while you fix it)")
        check(raised and os.environ["LITELLM_BASE_URL"] in raised,
              "the message names the endpoint that rejected us")
        check(raised and "401" in raised, "the message carries the real HTTP status")
        auth_attempts = re.findall(r"\[ai_router\] model '([^']+)' failed",
                                   buf3.getvalue())
        check(not auth_attempts,
              "the chain is NOT walked on an auth failure — every model shares "
              "the one key, so replaying it per model would bury the real cause")
        auth_rows = await conn.fetch(
            "SELECT * FROM ai_decision_log WHERE task_type = $1",
            TEST_TASK_TYPE + "_auth")
        check(len(auth_rows) == 1 and auth_rows[0]["success"] is False,
              "the auth failure is still RECORDED in ai_decision_log before "
              "raising")

        # AILiteLLMAuthError must survive call_claude_json's bare except.
        async def _boom(*_a, **_k):
            raise ex.AILiteLLMAuthError("simulated bad key")

        original = ex._execute_chain
        ex._execute_chain = _boom
        try:
            propagated = False
            try:
                await ex.call_claude_json("s", "u", org_id=ORG_ID)
            except ex.AILiteLLMAuthError:
                propagated = True
            except Exception:  # noqa: BLE001
                propagated = False
            check(propagated,
                  "AILiteLLMAuthError propagates through call_claude_json — it "
                  "is NOT flattened to None by that function's bare `except "
                  "Exception` (the trap this sprint had to dodge)")
            for fn in ("call_claude_text", "call_claude_with_tools"):
                prop = False
                try:
                    args = ("s", []) if fn == "call_claude_text" else ("s", [], [])
                    await getattr(ex, fn)(*args, org_id=ORG_ID)
                except ex.AILiteLLMAuthError:
                    prop = True
                except Exception:  # noqa: BLE001
                    prop = False
                check(prop, f"AILiteLLMAuthError also propagates through {fn}")
        finally:
            ex._execute_chain = original

    finally:
        # -------------------- TEARDOWN --------------------
        print("\n=== TEARDOWN ===")
        await conn.execute(
            "DELETE FROM ai_decision_log WHERE task_type = ANY($1::text[])",
            [TEST_TASK_TYPE, TEST_TASK_TYPE + "_rollback", TEST_TASK_TYPE + "_auth"])
        left = await conn.fetchval(
            "SELECT count(*) FROM ai_decision_log WHERE task_type LIKE $1",
            TEST_TASK_TYPE + "%")
        check(left == 0, f"zero leftover ai_decision_log rows (found {left})")
        # LiteLLM's spend log is deliberately NOT torn down. It is an external
        # service's own append-only audit trail, not our fixture — deleting from
        # it would be falsifying another system's records. What teardown must
        # prove instead is that this run cost nothing and left no configuration
        # behind on the live proxy.
        spend_end = await spend_log_count(conn)
        billed = await conn.fetchval(
            'SELECT coalesce(sum(spend), 0) FROM litellm."LiteLLM_SpendLogs" '
            'WHERE "startTime" >= $1', run_started_at)
        check(float(billed) == 0.0,
              f"this verify run billed $0.00 on the live proxy (rows added: "
              f"{spend_end - spend_before_all}, all failures)")
        s_final, b_final = http("/v1/models", key=os.environ.get(
            "LITELLM_MASTER_KEY", ""))
        check(s_final == 200 and json.loads(b_final).get("data") == [],
              "the live proxy's model deployment list is still empty — this run "
              "created no model on the shared service")
        check(os.environ.get(ex.LITELLM_DISABLE_VAR) is None,
              "the rollback switch is left DISENGAGED in the environment")
        try:
            from services.database import close_pool
            await close_pool()
        except Exception:  # noqa: BLE001
            pass
        await conn.close()

    passed = sum(1 for ok, _ in RESULTS if ok)
    total = len(RESULTS)
    print(f"\n{'=' * 72}")
    for ok, label in RESULTS:
        if not ok:
            print(f"  FAILED: {label}")
    print(f"RESULT: {passed}/{total} PASS")
    if BLOCKED:
        print(f"\n{len(BLOCKED)} BLOCKED — real external blockers, console action "
              f"required:")
        for b in BLOCKED:
            print(f"  * {b}")
    print("=" * 72)
    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
